# Generated by Django 5.0.2 on 2024-02-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0002_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='care_app.user')),
                ('name', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('pharmacy', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('medication', models.TextField()),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_caretaker', to='care_app.user')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_doctor', to='care_app.user')),
            ],
        ),
    ]
