# Generated by Django 5.0.2 on 2024-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0004_user_address_line_1_user_address_line_2_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
        migrations.AddField(
            model_name='medication',
            name='patient_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicine_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
