# Generated by Django 5.0.2 on 2024-02-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0006_alter_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
