# Generated by Django 5.0.2 on 2024-02-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0007_rename_patient_appointment_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_app.user'),
        ),
    ]
