# Generated by Django 5.0.2 on 2024-02-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0009_remove_medication_date_medication_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='day',
        ),
    ]
