# Generated by Django 5.0.2 on 2024-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0011_medication_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
